### ISSUE TITLE
Expose action type strings

### ISSUE THREAD

**Issue by andrewsantarin** [GA-MO/redux-modux#2]
Hi, @GA-MO. Interesting library. It cleans up a lot of the plumbing I need to do if I installed it. This is really nice if I want to scale up an app. I like that!

However, I feel there needs to be a way to expose the action's `type` attribute somewhere. For those of us who use [`redux-saga`](https://github.com/redux-saga/redux-saga), knowing which pattern to find for in asynchronous operations is very, very important to us. Operations like [`takeEvery(pattern: String | Array | Function, saga: Function, ...args: Array<any>)`](https://redux-saga.js.org/docs/api/#takeeverypattern-saga-args) listen for events, and one way we can do that is by setting the `pattern` argument to the action's `type` string.

**Example** (from `redux-saga`):
https://redux-saga.js.org/docs/basics/DeclarativeEffects.html, the `takeEvery` function is listening for an action type so that it can do the next step.

I won't bore you with the details of how `redux-saga` works, so, let me demonstrate using the code below.

**Example** (with your `redux-modux` in context):

```js
import UserService from 'user/user.service'; // axios
import UserModule from 'user/user.modules'; // redux-modux 

function* createUsers() {
  // ... redux-saga actions here that I won't explain for brevity.
}

function* updateUsers() {
  // ... redux-saga actions here that I won't explain for brevity.
}

function* deleteUsers() {
  // ... redux-saga actions here that I won't explain for brevity.
}

function* readUsers() {
  // UserModule.actionTypes.readUsersRequest == '@@reduxAction_user.readUsersRequest';
  // Expect this saga to take effect when '@@reduxAction_user.readUsersRequest' has been dispatched.
  // The `action` variable reads the dispatched action object from `take()`, which contains request parameters.
  const action = yield take(UserModule.actionTypes.readUsersRequest);

  try {
    // Request the /users REST API to return results.
    const response = yield call(UserService.readUsers, action.payload.params);

    // Dispatch the '@@reduxAction_user.readUsersSuccess' action when the request succeeds.
    // UserModule.actionTypes.readUsersSuccess == '@@reduxAction_user.readUsersSuccess';
    yield put(UserModule.readUsersSuccess({ payload: response }));
  } catch (exception) {
    // Dispatch the '@@reduxAction_user.readUsersFailure' action when the request fails.
    // UserModule.actionTypes.readUsersFailure == '@@reduxAction_user.readUsersFailure';
    yield put(UserModule.readUsersFailure({ error: exception }));
  }
}

// Listen for any CRUD REST API requests.
export default function* usersApiSaga() {
  yield all([
    fork(readUsers),
    fork(createUsers),
    fork(updateUsers),
    fork(deleteUsers),
  ]);
}
```

**Comment by GA-MO** [comment]
@andrewsantarin 
How about `UserModule.readUsersRequest.actionType` when want to use action's `type` string?
```js
  // UserModule.readUsersRequest.actionType == '@@reduxAction_user.readUsersRequest';
  const action = yield take(UserModule.readUsersRequest.actionType);
```

**Comment by andrewsantarin** [comment]
That's also one way to go about it, @GA-MO. You take the action creator function, then assign an `actionType` (or just `type`) property to it, or represent the action creator type through the function's `toString()` method.

On this file:

https://github.com/GA-MO/redux-modux/blob/a5fbe0a738e517d850d26e5cc236f813f51f7a6e/src/createAction.js#L8-L11

`actionType` as a property:

```diff
    const action = (payload = {}) => ({
      type: actionType,
      ...payload
    })

+    action.actionType = actionType // Or action.type = type. That's fine, too.
+    // Example: 
+    // console.log(addUser.actionType) // outputs 'ADD_USER';
```

`actionType` as a string representation of the function:

```diff
    const action = (payload = {}) => ({
      type: actionType,
      ...payload
    })

+    action.toString = () => actionType
+    // Example: 
+    // console.log(addUser) // outputs 'ADD_USER';
```

**Comment by GA-MO** [comment]
@andrewsantarin 
Thanks a lot this feature has been added in v.2.2.1

**Comment by andrewsantarin** [comment]
You're welcome, @GA-MO! I read the commit. Looks good to me.
